linters-settings:
  misspell:
    locale: US
  revive:
    ignore-generated-header: true

linters:
    enable:
    - goimports
    - govet
    - gofmt
    - revive
    - misspell
    disable-all: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
run:
  timeout: 5m
